// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dbs

import (
	"time"
)

type Account struct {
	ID     int64
	Number int64
	Name   string
}

type Deal struct {
	ID        int64
	AccountID int64
	// 0 - BUY, 1 - SELL
	Type       int32
	OpenPrice  string
	ClosePrice string
	OpenTime   time.Time
	CloseTime  time.Time
	Profit     string
}
